version: 0.2

env:
  variables:
    APP_NAME: "projeto-devops-back-end"
    JAR_NAME: "projeto-devops-back-end.jar"
    APP_DIR: "/opt/projeto-devops-back-end"

  secrets-manager:
    URL_DATABASE: "projeto-devops-back-end/prod:URL_DATABASE"
    DB_USERNAME: "projeto-devops-back-end/prod:DB_USERNAME"
    DB_PASSWORD: "projeto-devops-back-end/prod:DB_PASSWORD"
    AWS_BUCKET_NAME: "projeto-devops-back-end/prod:AWS_BUCKET_NAME"

phases:
  install:
    runtime-versions:
      java: corretto21

  pre_build:
    commands:
      - echo "========================================="
      - echo "INFORMAÇÕES DO AMBIENTE"
      - echo "========================================="
      - java -version
      - chmod +x mvnw
      - ./mvnw -version
      - 'test -n "$AWS_BUCKET_NAME" && echo "AWS_BUCKET_NAME definida" || echo "ERRO: AWS_BUCKET_NAME não definida"'

  build:
    commands:
      - echo "========================================="
      - echo "EXECUTANDO TESTES E BUILD"
      - echo "========================================="
      - ./mvnw clean package -DskipTests

  post_build:
    commands:
      - echo "========================================="
      - echo "PREPARANDO ARTEFATO PARA CODEDEPLOY"
      - echo "========================================="

      - mkdir -p deploy-artifact

      # Copia o JAR principal especificando o nome do arquivo gerado
      - cp target/${JAR_NAME} deploy-artifact/${JAR_NAME}
      - cp deploy/appspec.yml deploy-artifact/
      - cp -r deploy/scripts deploy-artifact/

      # Garante permissão de execução em todos os scripts do CodeDeploy
      - chmod +x deploy-artifact/scripts/*.sh

      - echo "===== COMMIT ====="
      - git rev-parse HEAD
      - echo "===== SHA256 JAR ====="
      - sha256sum deploy-artifact/${JAR_NAME}

      - echo "========================================="
      - echo "ESTRUTURA FINAL DO ARTEFATO"
      - echo "========================================="
      - find deploy-artifact -type f -print

artifacts:
  base-directory: deploy-artifact
  files:
    - "**/*"
  discard-paths: no