spring.application.name=projeto-devops-back-end

spring.datasource.url =${URL_DATABASE}
spring.datasource.username =${DB_USERNAME}
spring.datasource.password =${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

aws.bucket.name=${AWS_BUCKET_NAME}