spring.application.name=projeto-devops-back-end
spring.config.import=aws-secretsmanager:projeto-devops-back-end/prod
spring.cloud.aws.region.static=us-east-1
spring.datasource.url =${URL_DATABASE}
spring.datasource.username =${DB_USERNAME}
spring.datasource.password =${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
management.endpoints.web.exposure.include=health
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

aws.bucket.name=${AWS_BUCKET_NAME}