version: 0.0

os: linux

file_exists_behavior: OVERWRITE

files:
  - source: target/projeto-devops-back-end.jar
    destination: /opt/projeto-devops-back-end

hooks:

  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 60
      runas: root

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 120
      runas: root