version: 0.0

os: linux

#instrui o agente do CodeDeploy a substituir o .jar antigo pelo novo arquivo sem interromper a execução com erro de conflito.
file_exists_behavior: OVERWRITE

files:
  - source: target/projeto-devops-back-end.jar
    destination: /opt/projeto-devops-back-end

hooks:

  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 60
      runas: root

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 120
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: root