name: Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      URL_DATABASE: ${{ secrets.URL_DATABASE }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      AWS_BUCKET_NAME: ${{ vars.AWS_BUCKET_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::345594575506:role/github-actions-s3
          aws-region: us-east-1

      - name: Test AWS authentication
        run: aws sts get-caller-identity





